language: csharp
sudo: required
before_script: chmod ugo+x travis-run.sh
script: ./travis-run.sh

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none