language: csharp
sudo: required

services:
  - docker

script: 
  - dotnet restore
  - dotnet test ./SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/project.json

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-003121
    mono: none

#Docker section
after_success:
  - chmod ugo+x ./CodeDeploy/dockerDeploy.sh
  - ./CodeDeploy/dockerDeploy.sh