language: csharp
sudo: required
node_js: 
  - "node"
python:
  - "2.7"
install: 
  - pip install ecs-deploy
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

services:
  - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script: 
  - cd ./SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web
  - dotnet restore ../
  - dotnet build 
  - npm install 
  - grunt all
  - cd /home/travis/build/osu-cass/SampleItemsWebsite/
  - dotnet test ./SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/project.json

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-1-003177
    mono: none

#Docker section
after_success:
  - docker --version
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export PATH=$PATH:$HOME/.local/bin
  - dotnet publish /home/travis/build/osu-cass/SampleItemsWebsite/SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web -o /home/travis/build/osu-cass/SampleItemsWebsite/publish/
  - cd /home/travis/build/osu-cass/SampleItemsWebsite/publish/
  - docker build -t sampleitemscode .
  - docker tag sampleitemscode:latest osucass/sampleitemscode:$BRANCH
  - docker push osucass/sampleitemscode:$BRANCH
  - cd /home/travis/build/osu-cass/SampleItemsWebsite
  - chmod ugo+x DeployScripts/runEcsBuild.sh
  - ./DeployScripts/runEcsBuild.sh