language: csharp
sudo: required
before_script: cd ./SmarterBalanced.SampleItems
script: 
  - dotnet restore
  - dotnet test ./src/SmarterBalanced.SampleItems.Test/project.json

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none