language: csharp
sudo: required
dist: trusty
dotnet: 2.0.0
mono: none
node_js: 
  - "8"
python:
  - "2.7"
services:
  - docker

install: 
  - export PATH=$PATH:$HOME/.local/bin
  - cd $TRAVIS_BUILD_DIR/SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web
  - travis_retry npm install 
  - travis_retry dotnet restore
  - travis_retry dotnet restore ../SmarterBalanced.SampleItems.Test/

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$TRAVIS_PULL_REQUEST, BRANCH=$BRANCH"
  - echo "$TRAVIS_COMMIT"
  - export BUILD_NUMBER=$(echo $TRAVIS_BUILD_ID)
  - echo $BUILD_NUMBER

script: 
  - dotnet build 
  - cd $TRAVIS_BUILD_DIR/SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test
  - dotnet test 
  - dotnet publish $TRAVIS_BUILD_DIR/SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web -o $TRAVIS_BUILD_DIR/publish/

#Docker section
after_success:
  - docker --version
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - cd $TRAVIS_BUILD_DIR
  - chmod ugo+x DeployScripts/code_docker_deploy.sh
  - chmod ugo+x DeployScripts/app_docker_deploy.sh
  - chmod ugo+x DeployScripts/ecs_deploy.sh
  - chmod ugo+x DeployScripts/nuget_deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/code_docker_deploy.sh && ./DeployScripts/nuget_deploy.sh
    on:
        tags: true
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/nuget_deploy.sh "alpha-$BUILD_NUMBER" && ./DeployScripts/code_docker_deploy.sh
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/nuget_deploy.sh "pre-$BUILD_NUMBER" && ./DeployScripts/code_docker_deploy.sh
    on:
      branch: staging